on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: Fix ownership for newer git
        run: sudo git config --system --add safe.directory /github/workspace
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          PAGES_BRANCH: main
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: barendhemmes/hemmes.info.github.io
